name: "WoofChef"
description: "一个支持 AI 原材料识别的本地私有菜谱记忆系统。"
version: "1.0.1"
slug: "woofchef"
init: false
arch:
  - aarch64    # Jetson Xavier NX 的架构
  - amd64      # 兼容普通 PC
ports:
  5000/tcp: 5000
webui: http://[HOST]:[PORT:5000]
panel_icon: mdi:chef-hat
panel_title: "WoofChef 汪汪厨房"
map:
  - share:rw   # 可选：如果未来需要与其他插件共享文件